ej2-javascript/grid/ej2-typescript-grid-toc.html
ej2-javascript/pager/ej2-typescript-pager-toc.html

documentation(EJ2-71943): changed toc structure

---

ej2-javascript/code-snippet/grid/exporting-blob-data-cs1/index.js
ej2-javascript/code-snippet/grid/exporting-blob-data-cs2/index.js

documentation(EJ2-71943): issue resolved

---

ej2-javascript/grid/ej2-javascript-grid-toc.html
ej2-javascript/grid/ej2-typescript-grid-toc.html

documentation(EJ2-71943): Added Api Reference

---

ej2-javascript/grid/ej2-javascript-grid-toc.html
ej2-javascript/grid/ej2-typescript-grid-toc.html
ej2-javascript/pager/ej2-javascript-pager-toc.html
ej2-javascript/pager/ej2-typescript-pager-toc.html

documentation(EJ2-71943): Added API in Toc

---

Jenkinsfile

documentation(EJ2-71942): Added jenkins File

---

Jenkinsfile

documentation(830451): Added jenkins file

---

ej2-javascript/grid/columns/columns.md
ej2-javascript/grid/editing/template-editing.md
ej2-javascript/grid/index.md
ej2-javascript/grid/virtual-scroll.md

Documentation(833199): Fixed Broken link issue

---

ej2-javascript/grid/js/getting-started.md
ej2-javascript/grid/ts/getting-started.md

Need to resolve the Page With Redirect - EJ2 docs links for grid documentation
Resolved the Page With Redirect - EJ2 docs links for grid documentation by adding the correct links
NA
No area is affected due to this changes.
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? No
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? NA

documentation(839873): Add the correct path.

---

ej2-javascript/grid/columns/columns.md
ej2-javascript/grid/grouping/grouping.md
ej2-javascript/grid/hierarchy-grid.md
ej2-javascript/grid/how-to/customize-the-edit-dialog.md
ej2-javascript/grid/sorting.md
ej2-javascript/pager/ts/getting-started.md

Resolved Broken links issue for Grid component

bug(839526): Resolved broken link issue for Grid component

---

ej2-javascript/grid/frozen.md

Documentaion content update for Frozen rows and columns

doc(EJ2-845673): Documentaion content update for Frozen rows and columns 

---

ej2-javascript/grid/frozen.md

Updated the module changes in frozen rows and columns sample.

doc(EJ2-845673): Updated the module changes in frozen rows and columns sample.

---

ej2-javascript/code-snippet/grid/export-mutiple-grid-cs1/index.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs1/index.ts
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs2/index.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs2/index.ts
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs3/index.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/datasource.ts
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/es5-datasource.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/index.css
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/index.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/index.ts
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/js/index.html
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/systemjs.config.js
ej2-javascript/code-snippet/grid/export-mutiple-grid-cs4/ts/index.html
ej2-javascript/grid/excel-export/export-multiple-grids.md
ej2-javascript/grid/pdf-export/export-multiple-grids.md

Updated the topics multiple grid exporting in PDF and Excel exporting of grid component.

Documentation(EJ2-847476): Multiple Grid PDF and Excel exporting 

---

ej2-javascript/grid/excel-export/export-multiple-grids.md
ej2-javascript/grid/pdf-export/export-multiple-grids.md

Updated the limitations for multiple grid export.

Documentation(EJ2-847476):Multiple-Grid-Export Content updated

---

ej2-javascript/code-snippet/grid/caption-template-export-cs1/index.js
ej2-javascript/code-snippet/grid/caption-template-export-cs1/index.ts
ej2-javascript/code-snippet/grid/caption-template-export-cs1/systemjs.config.js
ej2-javascript/code-snippet/grid/caption-template-export-cs2/index.js
ej2-javascript/code-snippet/grid/caption-template-export-cs2/index.ts
ej2-javascript/code-snippet/grid/caption-template-export-cs2/systemjs.config.js
ej2-javascript/code-snippet/grid/column-template-export-cs1/index.js
ej2-javascript/code-snippet/grid/column-template-export-cs1/index.ts
ej2-javascript/code-snippet/grid/column-template-export-cs1/systemjs.config.js
ej2-javascript/code-snippet/grid/column-template-export-cs2/index.js
ej2-javascript/code-snippet/grid/column-template-export-cs2/index.ts
ej2-javascript/code-snippet/grid/column-template-export-cs2/systemjs.config.js
ej2-javascript/code-snippet/grid/detail-template-export-cs1/systemjs.config.js
ej2-javascript/code-snippet/grid/detail-template-export-cs2/systemjs.config.js
ej2-javascript/grid/ej2-javascript-grid-toc.html
ej2-javascript/grid/pdf-export/exporting-with-templates.md
ej2-javascript/grid/row/detail-template.md

Added detail template exporting topic in PDF and Excel exporting of grid component.

Doc(848333): added the notifications packages

---

ej2-javascript/code-snippet/grid/row-spanning-cs1/index.js
ej2-javascript/code-snippet/grid/row-spanning-cs1/index.ts
ej2-javascript/code-snippet/grid/row-spanning-cs1/js/index.html
ej2-javascript/code-snippet/grid/row-spanning-cs1/systemjs.config.js
ej2-javascript/code-snippet/grid/row-spanning-cs1/ts/index.html
ej2-javascript/grid/row/row-spanning.md

Modified the row spanning sample and content

EJ2-Documentation(850089)- UG documentation for row spanning

---

ej2-javascript/grid/accessibility.md

Tested the below cases in the share point page and updated the document based on this.
[Accessibility improvement (sharepoint.com)](https://syncfusion.sharepoint.com/sites/EJ2-ClientSide/SitePages/Accessibility-improvement.aspx?OR=Teams-HL&CT=1699535162259&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzEwMTIyNDgwNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)

Documentation(EJ2-859048):Accessibility document of Grid Component 

---

ej2-javascript/grid/row/row-template.md

Modified the sample name

---

ej2-javascript/grid/accessibility.md

Updated Keyboard compatibility in accessibility document

Documentation(EJ2-861810):Accessibility-content Keyboard compatibility update

---

ej2-javascript/grid/accessibility.md

Grid Accessibility Content updated

Documentation(EJ2-859048): Grid Accessibility Content update

---

ej2-javascript/code-snippet/grid/empty-record-template-cs1/datasource.ts
ej2-javascript/code-snippet/grid/empty-record-template-cs1/emptyRecordTemplate.svg
ej2-javascript/code-snippet/grid/empty-record-template-cs1/es5-datasource.js
ej2-javascript/code-snippet/grid/empty-record-template-cs1/index.css
ej2-javascript/code-snippet/grid/empty-record-template-cs1/index.js
ej2-javascript/code-snippet/grid/empty-record-template-cs1/index.ts
ej2-javascript/code-snippet/grid/empty-record-template-cs1/js/index.html
ej2-javascript/code-snippet/grid/empty-record-template-cs1/systemjs.config.js
ej2-javascript/code-snippet/grid/empty-record-template-cs1/ts/index.html
ej2-javascript/grid/ej2-javascript-grid-toc.html
ej2-javascript/grid/ej2-typescript-grid-toc.html
ej2-javascript/grid/how-to/customize-the-empty-record-template.md

Creating UG document for Empty record template

TASK 861830 - Creating UG document for Empty record template

---

ej2-javascript/grid/ej2-javascript-grid-toc.html
ej2-javascript/grid/ej2-typescript-grid-toc.html
ej2-javascript/grid/performance.md

documentation(ej2-1010):performance tips

---

ej2-javascript/grid/adaptive.md
ej2-javascript/grid/cell/cell.md
ej2-javascript/grid/grouping/grouping.md
ej2-javascript/grid/tool-bar.md
ej2-javascript/grid/virtual-scroll.md

Hi @Aishwarya-Ganesan ,
I have changed the redirection links, please review.
Regards,
Scholar.

SEO-178903-Page-With-Redirect

---

ej2-javascript/grid/columns/column-spanning.md
ej2-javascript/grid/row/row-spanning.md

Need to add the limitation of column spanning and row spanning in all platform

Doc(867101):Need to add the limitation of column spanning and row spanning in all platform

---

ej2-javascript/grid/row/row.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-179239-Redirect-Links-TS

---

ej2-javascript/grid/searching.md

Hi @Aishwarya-Ganesan,
I have changed redirection links, please review.
Regards,
Scholar.

SEO-179238-Page-with-redirect

---

ej2-javascript/grid/editing/edit.md

Hi @MallikaRK ,
Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-ej2-js-grid-page-with-redirect-link

---

ej2-javascript/code-snippet/grid/grid-cs13/index.js
ej2-javascript/code-snippet/grid/grid-cs13/index.ts
ej2-javascript/grid/row/row-spanning.md

ODataAdaptor URL is not working in DataManager

Doc(856309):ODataAdaptor URL is not working in DataManager

---

ej2-javascript/grid/style-and-appearance/style-and-appearance.md

Hello,
I have worked on links with redirects,
Regards,
Beryl

SEO-179239-Redirect-Links-Vue

---

ej2-javascript/grid/getting-started.md
ej2-javascript/grid/tool-bar/tool-bar.md

Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.

SEO-178901-ej2-js-grid-redirect-links

---

ej2-javascript/grid/hierarchy-grid.md

Hi @MallikaRK,
Worked on page with redirect for Grid.
Regards,
Sharly A.

SEO-179237-Grid-doc-changes

---

ej2-javascript/grid/data-binding/data-binding.md

Hi @MallikaRK,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-179251-ej2-js-grid

---

ej2-javascript/grid/columns/columns.md
ej2-javascript/grid/how-to/change-hierarchy-grid-icon.md

Hi @MallikaRK
Worked on js grid docs changes.
Regards,
Sharly A.

SEO-179773-JS-Grid-Changes

---

ej2-javascript/grid/columns/column-spanning.md
ej2-javascript/grid/frozen.md
ej2-javascript/grid/grouping/grouping.md
ej2-javascript/grid/infinite-scroll.md
ej2-javascript/grid/row/row-spanning.md
ej2-javascript/grid/virtual-scroll.md

Need to add the limitation for feature wise in all platform

Doc(871078):Need to add the limitation for feature wise in all platform
